ansible_ssh_private_key_file: /home/adminUsername/.ssh/id_rsa_cp2

master_address: "20.229.49.162"
worker01_address: "20.229.50.105"
worker02_address: "20.229.50.94"
nfs_address: "20.229.49.150"

pod_network_cidr: "192.169.0.0/16"

workers_rule:
  - "rule family=ipv4 source address=20.229.50.105/32 accept"
  - "rule family=ipv4 source address=20.229.50.94/32 accept"

kube_perm_workers_rule: rule family=ipv4 source address=172.17.0.1/16 accept

variable_host_sdn: ["master", "workers"]
uusername_admink8s: kubeadmin
upassword_admink8s: 123
