---
- name: Creando el usuario "kubeadmin" con acceso de administrador, para la gestión del clúster
  user:
    name: kubeadmin
    password: 123

- name: Contraseña que expira para la usuario "kubeadmin"
  shell: chage -d 0 "kubeadmin"

- name: Se copia la configuracion del kluster al usuario
  shell: |
    mkdir -p /home/kubeadmin/.kube
    sudo cp /etc/kubernetes/admin.conf /home/kubeadmin/.kube/config
    chown kubeadmin. /home/kubeadmin/.kube/config

- name: Agregando usuario "kubeadmin" a sudoers
  blockinfile:
    create: yes
    path: "/etc/sudoers.d/kubeadmin"
    block: |
      ALL            ALL = (ALL) NOPASSWD: ALL
