---
- name: Tareas previas de configuración
  hosts: all
  gather_facts: false
  become: true
  roles:
    - config_general

# # - name: instalar servidor NFS
# #   hosts: nfs
# #   gather_facts: false
# #   become: true
# #   roles:
# #     - "nfs"

- name: Tareas comunes a realizar en el nodo master y los workers
  hosts: all
  gather_facts: false
  become: true
  roles:
    - k8config

# - name: Configurando kubernetes en el nodo master
#   hosts: master
#   gather_facts: false
#   become: true
#   roles:
#     - k8master

# - name: configuracion sdn calico
#   hosts: master
#   gather_facts: false
#   become: true
#   roles:
#     - sdn_calico

# - name: configurando kubernetes en workers
#   hosts: workers
#   gather_facts: false
#   become: true
#   roles:
#     - k8workers

# - name: Instalando ingress controller
#   hosts: master
#   gather_facts: false
#   become: true
#   roles:
#     - ingress-controller

# - name: Creando usuarios
#   hosts: master
#   gather_facts: false
#   become: true
#   roles:
#     - users
