---
- name: Lo primero que tenemos que hacer en los workers es abrir los puertos
  firewalld:
    zone: public
    permanent: yes
    state: enabled
    immediate: yes
    port: "{{ item }}"
  loop:
    - 10250/tcp
    - 30000-32767/tcp

- name: Reiniciar firewall
  command: firewall-cmd --reload

- name: Copiar join command de master a los workers.
  copy:
    src: /tmp/kubernetes_join_command
    dest: /tmp/kubernetes_join_command
    mode: 0777

- name: Ahora para unirse al clúster tendremos que ejecutar en los nodos el comando de kubeadm que nos produjo la ejecución de kubadmin init
  command: sh /tmp/kubernetes_join_command
